### ISSUE TITLE
Intermittend test failure while running `cargo test` 

### ISSUE THREAD

**Issue by gabhijit** [gabhijit/intermodal#5]
An intermittent failure is observed while running `cargo test`. This has got to do with the downloaded 'temporary' blob file not found.

An error like following is seen 

```
thread 'image::docker::tests::test_get_image_inspect' panicked at 'ref: "//127.0.0.1:33869/library/fedora:latest", Err(ImageError { cause: Some(ClientError("No such file or directory (os error 2)")) })', src/image/docker/tests.rs:159:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
   2: intermodal::image::docker::tests::test_get_image_inspect::{{closure}}
             at ./src/image/docker/tests.rs:159
```

**Comment by gabhijit** [comment]
This issue is not observed for a while. So closing the issue.
